### ISSUE TITLE
Error SQLITE_ERROR: near ",": syntax error

### ISSUE THREAD

**Issue by mdunaiski** [davidyaha/sqlite-to-mongo#3]
Following error message is outputed when running a very simple config (identical to the example, just different names)

~~~~
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
/home/martin/migration/node_modules/sqlite-to-mongo/lib/SqliteToMongo.js:146
      if (err) throw new Error(err);
               ^

Error: Error: SQLITE_ERROR: near ",": syntax error
    at completeCallback (/home/martin/migration/node_modules/sqlite-to-mongo/lib/SqliteToMongo.js:146:22)
    at Statement.errBack (/home/martin/migration/node_modules/sqlite3/lib/sqlite3.js:16:21)
~~~~

I have tried it on several systems, same issue occurs

**Comment by davidyaha** [comment]
Hey @mdunaiski,
Could you share the sql string you are using? Or is it just a map between column name mongo field name?

**Comment by mdunaiski** [comment]
It is just a simple mapping

~~~~
const SqliteToMongo = require('sqlite-to-mongo');

var importer = new SqliteToMongo('sqlitedb.db', 'mongodb://localhost:3001/db');

importer.importCollection('test', {
  tableName : "sqltable",
  columns: {
    'ID': '_id',
    'SURNAME': 'surname',
    'NAME': 'name'
  }
});
~~~~

**Comment by davidyaha** [comment]
Does this typo exists in your codebase?
```
 tableName : "sqltable,
```

**Comment by davidyaha** [comment]
Even if not, this line looks suspicious:
https://github.com/davidyaha/sqlite-to-mongo/blob/master/lib/SqliteToMongo.js#L139

Would you mind changing that to `-2` and check if that works for you?
This is really old code and I would just use `join` today.. :/

**Comment by davidyaha** [comment]
might even be something that requires parenthesis...

**Comment by mdunaiski** [comment]
yes sorry, the typo was from me anonymising the code. The actual code does have the proper syntax (I have editied the comment)

Changing said line to -2 did not help, same error.

**Comment by davidyaha** [comment]
Could you console.log the query variable just after the line 142?

**Comment by Phobs** [comment]
Hi, the issue is that it never connects to mongo. I've gotten that same error when I didn't put in a query.
`importer.importCollection('users', {
  query:  'SELECT * FROM CurrencyUser ',
  columns: {
    name: 'Name',
    rank: 'Rank',
    points : 'Points',
},
});`

Adding the query solved that issue but instead brought about another.
`\node_modules\sqlite-to-mongo\lib\SqliteToMongo.js:55
  var collection = this.mongoDb.collection(collectionName);
`
I console logged a few things and noticed this.mongoDb is undefined because it doesn't seem to connect to mongo my guess is that something is up with:
`
  this.sqliteDb.once('open', mongo.connect.bind(this, mongoUrl, this._connected.bind(this, cb)));
`

**Comment by sertal70** [comment]
@davidyaha I confirm, that line requires parenthesis to work properly.

error--> `query += column + (index < columnNames.length - 1) ? ', ' : ' ';`

right--> `query += column + ((index < columnNames.length - 1) ? ', ' : ' ');`
